(i) SELECT * FROM CUSTOMERS WHERE CITIES NOT IN ('DELHI','MUMBAI');
(ii) SELECT CNAME, CITIES FROM CUSTOMERS ORDER BY CNAME ASC;
(iii) SELECT COUNT(*) AS 'Number of Customers', CITIES FROM CUSTOMERS GROUP BY CITIES;
(iv) SELECT * FROM PURCHASES WHERE QTY > 15;
(v) SELECT CUSTOMERS.CNAME, PURCHASES.QTY, PURCHASES.PUR_DATE FROM CUSTOMERS INNER JOIN PURCHASES ON CUSTOMERS.CNO = PURCHASES.CNO WHERE QTY = 10 OR QTY = 20;
(vi) SELECT MAX(PUR_DATE) FROM PURCHASES;